name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: home-assistant/actions/hassfest@master

  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hacs/action@main
        with:
          category: integration
